<?php

namespace UserBundle\Repository;

/**
 * FactureFreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureFreeRepository extends \Doctrine\ORM\EntityRepository
{
}
