<?php

namespace UserBundle\Repository;

/**
 * JustifTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustifTRepository extends \Doctrine\ORM\EntityRepository
{
}
