<?php

namespace UserBundle\Repository;

/**
 * JustifNDFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JustifNDFRepository extends \Doctrine\ORM\EntityRepository
{
}
