<?php


namespace UserBundle\Repository;

/**
 * AffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteRepository extends \Doctrine\ORM\EntityRepository
{

}